abbreviation_dict = {
    "ko": "không",
    "k": "không",
    "kg": "không",
    "khg": "không",
    "hok": "không",
    "ntn": "như thế nào",
    "tk": "tài khoản",
    "đc": "được",
    "dc": "được",
    "tl": "trả lời",
    "bt": "bình thường",
    "thks": "thanks",
    "tks": "thanks",
    "ty": "tình yêu",
    "ny": "người yêu",
    "ck": "chồng",
    "vk": "vợ",
    "add": "address",
    "ad": "admin",
    "ava": "avatar",
    "bb": "bye bye",
    "clgt": "cái l*n gì thế",
    "đkm": "địt mẹ",
    "vl": "vãi l*n",
    "vkl": "vãi cả l*n",
    "klq": "không liên quan",
    "cx": "cũng",
    "đcmm": "địt con mẹ mày",
    "đm": "địt mẹ",
    "vch": "vãi chưởng",
    "vcc": "vãi cả c*t",
    "ib": "inbox",
    "qtv": "quản trị viên",
    "gg": "google",
    "fb": "facebook",
    "atm": "automatic teller machine",
    "m": "mày",
    "mik": "mình",
    "tr": "triệu",
    "s": "sao",
    "đ": "đồng",
    "kz": "khoảng",
    "j": "gì",
    "ck": "chuyển khoản",
    "cn": "chủ nhật",
    "pt": "phương tiện",
    "cn": "công nghệ",
    "hh": "hoa hồng",
    "hnay": "hôm nay",
    "hqua": "hôm qua",
    "thứ 2": "thứ hai",
    "thứ 3": "thứ ba",
    "thứ 4": "thứ tư",
    "thứ 5": "thứ năm",
    "thứ 6": "thứ sáu",
    "thứ 7": "thứ bảy",
    "ck": "chuyển khoản",
    "acc": "account",
    "hth": "hoàn thành",
    "hh": "hoa hồng",
    "lh": "liên hệ",
    "chx": "chưa",
    "nx": "nói",
    "mn": "mọi người",
    "stt": "status",
    "mt": "mặt tiền",
    "qh": "quan hệ",
    "sn": "sinh nhật",
    "tn": "tin nhắn",
    "kn": "kỷ niệm",
    "sv": "sinh viên",
    "hs": "học sinh",
    "thcs": "trung học cơ sở",
    "thpt": "trung học phổ thông",
    "cn": "chủ nhật",
    "bqt": "ban quản trị",
    "trc": "trước",
    "sdt": "số điện thoại",
    "đt": "điện thoại",
    "vs": "với",
    "trg": "trong",
    "pls": "please",
    "u": "you",
    "f": "facebook",
    "ko": "không",
    "là": "là",
    "dc": "được",
    "đc": "được",
    "thấy": "thấy",
    "a": "anh",
    "e": "em",
    "v": "vậy",
    "vs": "với",
    "nh": "nhưng",
    "kh": "không",
    "th": "thấy",
    "ch": "chưa",
    "h": "hỏi",
    "c": "chị",
    "biết": "biết",
    "n": "nó",
    "ng": "người",
    "ko": "không",
    "oh": "ồ",
    "nchung": "nói chung",
    "cl": "cái l*n",
    "o": "ở",
    "thế": "thế",
    "giờ": "giờ",
    "nt": "nhắn tin",
    "g": "giờ",
    "khác": "khác",
    "tr": "triệu",
    "ph": "phút",
    "đ": "đồng",
    "b": "bạn",
    "fb": "facebook",
    "v": "và",
    "y": "yêu",
    "m": "mình",
    "km": "khuyến mãi",
    "nv": "nhân viên",
    "q": "quận",
    "tp": "thành phố",
    "lh": "liên hệ",
    "dt": "điện thoại",
    "stt": "status",
    "qh": "quan hệ",
    "tn": "tin nhắn",
    "kn": "kỷ niệm",
    "sv": "sinh viên",
    "hs": "học sinh",
    "thcs": "trung học cơ sở",
    "thpt": "trung học phổ thông",
    "cn": "chủ nhật",
    "bqt": "ban quản trị",
    "trc": "trước",
    "sdt": "số điện thoại",
    "đt": "điện thoại",
    "vs": "với",
    "trg": "trong",
    "pls": "please",
    "u": "you",
    "f": "facebook",
    "ok": "okay",
    "gts": "giải thích",
    "gđ": "gia đình",
    "bs": "bác sĩ",
    "kh": "khoa học",
    "hs": "học sinh",
    "gv": "giáo viên",
    "sv": "sinh viên",
        "sp": "sản phẩm",
    "nv": "nhân viên",
    "shop": "cửa hàng",
    "vd": "ví dụ",
    "kh": "khách hàng",
    "gh": "giao hàng",
    "tn": "tin nhắn",
    "qc": "quảng cáo",
    "tt": "thanh toán",
    "km": "khuyến mãi",
    "bh": "bảo hành",
    "hd": "hướng dẫn",
    "dt": "điện thoại",
    "tv": "tư vấn",
    "nx": "nhận xét",
    "ck": "chuyển khoản",
    "dv": "dịch vụ",
    "td": "thời gian",
    "cn": "chính hãng",
    "mg": "mã giảm",
    "dh": "đơn hàng",
    "ht": "hỗ trợ",
    "qn": "quận",
    "tp": "thành phố",
    "cc": "chất lượng",
    "tq": "tốt quá",
    "tuyệt": "tuyệt vời",
    "đẹp": "đẹp lắm",
    "giá": "giá rẻ",
    "k": "không",
    "r": "rất",
    "thjk": "thích",
    "sz": "size",
    "màu": "màu sắc",
    "mn": "mọi người",
    "đc": "được",
    "bt": "bình thường",
    "vv": "vân vân",
    "khá": "khá tốt",
    "ok": "đồng ý",
    "ko": "không",
    "dc": "được",
    "cmt": "bình luận",
    "rep": "trả lời",
    "fb": "Facebook",
    "gg": "Google",
    "zalo": "Zalo",
    "yt": "YouTube",
    "ib": "nhắn tin riêng",
    "stt": "status",
    "thks": "cảm ơn",
    "ck": "chuyển khoản",
    "đh": "đơn hàng",
    "pt": "phương tiện",
    "bh": "bảo hành",
    "gt": "giới thiệu",
    "bh": "bảo hiểm",
    "dt": "điện thoại",
    "ht": "hỗ trợ",
    "lv": "làm việc",
    "ql": "quản lý",
    "p": "phòng",
    "tl": "trả lời",
    "mt": "màn hình",
    "ad": "quản trị viên",
    "tt": "thông tin",
    "kb": "kết bạn",
    "kb": "kết nối",
    "dn": "đăng nhập",
    "đk": "đăng ký",
    "ns": "nhân sự",
    "pc": "máy tính",
    "cb": "cân bằng",
    "th": "thực hành",
    "ht": "hoàn thành",
    "qđ": "quy định",
    "qt": "quy trình",
    "kh": "kế hoạch",
    "nv": "nhân viên",
    "ch": "chất lượng"
}
# Ghi từ điển ra tệp văn bản
with open("tuviettat.txt", "w", encoding="utf-8") as file:
    for key, value in abbreviation_dict.items():
        file.write(f"{key},{value}\n")
